### ISSUE TITLE
Testing Vocab

### ISSUE THREAD

**Issue by Hedgehog-From-Outerspace** [Hedgehog-From-Outerspace/sign-vocab-test#2]
# User Stories
3. As a student, I want to select lessons and start a test to practice my vocabulary.
4. As a student, I want to see a random word from the selected lessons so I can practice different signs.
5. As a student, I want to mark my attempts as correct or incorrect and view the results.

# Tasks

- [ ] Add a test button to start a test for selected lessons.
- [ ] Randomize and display words during the test.
- [ ] Allow users to mark attempts as correct or incorrect.
- [ ] Calculate and display test results.
